Get config from server
mage/mage-sdk-js pull request #7
Opened 2018-04-27 09:51 UTC by Nokitoo

Changed Mage SDK setup process:
- No longer need to feed Webpack with mage.getClientConfig
- Add Mage.setEndpoint to setup server endpoint
- add Mage.init to fetch config from the Mage server

Fixes mage/mage#239

2018-05-11 02:07 UTC, stelcheck requested changes
Overall it goes in the right direction.

2018-05-11 02:07 UTC, stelcheck commented on docs/ReadMe.md
> +To init the sdk, your MAGE server needs to expose the client config.
SDK, not sdk.

2018-05-11 02:07 UTC, stelcheck commented on docs/ReadMe.md
> +	'game' 				// App name
We could make this optional (default: 'game')

2018-05-11 02:07 UTC, stelcheck commented on docs/ReadMe.md
> +// Init mage sdk
SDK

2018-05-11 02:07 UTC, stelcheck commented on docs/ReadMe.md
> +		return;
Should at least log

2018-05-11 02:07 UTC, stelcheck commented on lib/Mage.js
> +		throw new Error('Please call Mage.setEndpoint before calling Mage.init');
mage.setInstance; `Mage...` looks like a static method.

2018-05-11 02:07 UTC, stelcheck commented on lib/Mage.js
> +	var hr = new HttpRequest({
I think we discussed this, but can't we use `sendCommand` somehow? For the record, why couldn't we use it?

2018-05-11 03:23 UTC, Nokitoo commented on lib/Mage.js
> +	var hr = new HttpRequest({
Because the `CommandCenter` need the config to setup.

2018-05-16 04:22 UTC, Nokitoo commented
I don't know if it should be in this PR or a new one, but I think we should definitely remove all client related config from the server config.
For example, `server.msgStream.detect` is only used by the SDK to know in what order it should attempt to create protocols.

2018-05-16 05:42 UTC, stelcheck commented
We can do this in another PR, yes.

2018-07-27 08:27 UTC, stelcheck approved these changes

2018-07-27 08:27 UTC, merged